### ISSUE TITLE
JSON endpoint returns invalid JSON

### ISSUE THREAD

**Issue by lordblendi** [Medium/medium-api-docs#101]
Hi!

I'm trying to get latest posts via a curl call: 
``` bash
curl -H 'Accept: application/json'  "https://medium.com/@test/latest"
```

But the json, it returns is invalid. I used the username "test", so the answer is smaller and I can copy it here:

``` json
])}while(1);</x>{"success":false,"error":"User deactivated or deleted their account","v":3,"b":"29331-a7bc9d3","errorInfo":{"code":-1}}⏎      
```

It doesn't matter if it's n existing user or not, but the `])}while(1);</x>` is always at the front.

It would be nice if you could fix this. Thanks!

**Comment by newhouse** [comment]
Hi @lordblendi. This is actually _intentional_ on behalf of Medium to prevent JSON Hijacking. You can learn a bit more [here](https://github.com/Medium/medium-api-docs/issues/73) and see at least one solution example.

Also, if you plan on using Medium's API you should probably know one thing: it seems fair to conclude that Medium  doesn't care at all about supporting or enhancing this API, since I've not seen any activity in this repo from them in the 6+ months or so that I've been watching it. Thankful to have it, but bummer!

**Comment by lordblendi** [comment]
Hi @newhouse!

Ah, thank you, makes more sense now. I'm writing only a "one time script" to get all my posts from medium and convert them to markdown files, so for me, it's still okay like this :) But of course it would be nicer, if they would still care about this API.

**Comment by jordanbrauer** [comment]
> Also, if you plan on using Medium's API you should probably know one thing: it seems fair to conclude that Medium doesn't care at all about supporting or enhancing this API, since I've not seen any activity in this repo from them in the 6+ months or so that I've been watching it. Thankful to have it, but bummer!

@newhouse This explains a lot. Thanks 😃

**Comment by MediumEng** [comment]
The private JSON API is unsupported (and using it is technically against the [terms of service](https://medium.com/policy/medium-terms-of-service-9db0094a1e0f))
