### ISSUE TITLE
User has reached the rate limit for publishing today.

### ISSUE THREAD

**Issue by web2033** [Medium/medium-api-docs#105]
I'm getting this response:
`User has reached the rate limit for publishing today.`
Where I can find information about rate limits for publishing.
Is it 10 or something posts per day?
Any other restrictions?

**Comment by Ivan-Cantarino** [comment]
@web2033 did you found out the limit? I'm currently having the same error

**Comment by Ivan-Cantarino** [comment]
@web2033 I have found out it is 10 posts - sad for developer testing

**Comment by web2033** [comment]
@Ivan-Cantarino Hi! Correct, 10.

**Comment by Ivan-Cantarino** [comment]
I don’t know when the limit resets. And as far as I’m concerned you’ve to email them in order to request the limits to be expanded. And to upload images you’ll need as well a specific permission. 

Important to mention that I have sent them and resent after, emails requesting this and haven’t got a reply in 2 months — a complete share tbh

**Comment by MediumEng** [comment]
Unfortunately 10 is correct (we had to set it pretty low due to abuse/spam). It will reset 24 hours after the initial post.
