### ISSUE TITLE
Feature requests: update a post, post stats

### ISSUE THREAD

**Issue by satyavh** [Medium/medium-api-docs#22]
First of all, the API works great. Thanks for that!
Here are some ideas that I could use, but I can imagine will be useful for other devs as well:

### Update a post
Updating a post's title, content, published status.
(useful if you posted something wrong / need to change something)

### Post stats
How is my post doing at Medium?
(I think this is very interesting for data aggregation - like comparing your content performance on different channels).

Perhaps add your vote / ideas in the comments?

**Comment by aciidb0mb3r** [comment]
Highly interested in stats API even if basic to start with

**Comment by majelbstoat** [comment]
Update post is on the roadmap, though no specific timeframe to share at the moment.

Nothing to share regarding stats at the moment.

**Comment by oldcookie** [comment]
+1 for updating a Post, especially post status.   It's hard to do an API based workflow if it's not possible to submit a post as private, preview then change the status to public

**Comment by huckphin** [comment]
Editing a post is on the roadmap, but there is no specific plans right now. I will be taking this to the next round of product planning to see what is next.

There is no stats API on the roadmap right now, but will bring that specific suggestion to the next round of product planning. Thank you for the suggestion.

**Comment by KarlPGalvez** [comment]
Any update on editing a post? This is a crucial feature for a project I am planning.

**Comment by mandersondesign** [comment]
I would like to follow up on @KarlPGalvez point (which i referenced in another issue) that it would be great to be able to update the publish date of the post (in the UI is best... in the API is second best) so we can accurately indicate which posts were published when, if we have to import from a URL.

Importing our blog from Hubspot... lot's of manual labor in this since they make it hard hard hard to leave.

**Comment by erbear** [comment]
Is there any update on updating post? Any timeline when it can be implemented?

**Comment by kylehg** [comment]
Unfortunately a post editing API isn't currently being prioritized by any of our teams and we don't have any immediately plans to do so. I'm going to close this issue so as not to mislead folks.

**Comment by buhrmi** [comment]
Closing this issue is more misleading than leaving it open...

**Comment by kandebonfim** [comment]
C'mon, guys! How this is not a priority?

**Comment by kuon** [comment]
I'd like to keep publishing to medium, but not being able to update posts make it much harder as I'd like to write once in markdown and publish to different platforms.

**Comment by mcclowes** [comment]
Big priority for me also (both updating posts & stats). Realistically, not everyone wants to write directly into the Medium editing interface, no matter how nice it is.

**Comment by pdavide** [comment]
+1 for updating a post

**Comment by mdavarynejad** [comment]
+1 for stats API

**Comment by RickStrahl** [comment]
Clearly this is a political issue at Medium - they want you to use their side. Surely it's not a difficult technical task given that you **can** post one time. We do this in [Markdown Monster](https://markdownmonster.west-wind.com), but it's more of a hassle than it's worth because invariably people ask - "WTF can't I update my post as I can with Wordpress or MetaWeblog API".

Total fail on Medium's part, but I wouldn't hold out for a solution... it ain't going to happen if it hasn't happened yet.

**Comment by rarenal** [comment]
Please reopen this!! @kylehg

**Comment by SilencerWeb** [comment]
+1 for updating a post

**Comment by reduxdj** [comment]
Come on, guys, not offering this ability is kinda **# L**ame with a capital L

**Comment by reduxdj** [comment]
it's been 3 years already.... can't you guys/girls make a full-featured API, it's the year 2018.
